# Generated by Django 4.1.5 on 2023-01-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Наполенение статьи'),
        ),
    ]
